# JACKSON
spring:
    thymeleaf:
        cache: false


# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8087}
    context-path: /
    error.whitelabel.enabled: false
    compression:
      enabled: true
      min-response-size: 1024
      mime-types:
          - text/html
          - text/css
          - text/plain
          - text/xml
          - application/json
          - application/javascript
